Lint fixes
Fixes the following warnings and errors picked up by puppet-lint, and
ignores the warning about quoted booleans (alternatives are to use
stdlib's `str2bool`, or wait until 3.7 gains more traction and the
default is changed, see
https://docs.puppetlabs.com/puppet/latest/reference/lang_facts_and_builtin_vars.html#data-types)

The full list of resolved lint problems:
    WARNING: top-scope variable being used without an explicit namespace on line 74
    WARNING: top-scope variable being used without an explicit namespace on line 74
    WARNING: top-scope variable being used without an explicit namespace on line 156
    WARNING: quoted boolean value found on line 74
    WARNING: quoted boolean value found on line 156
    ERROR: two-space soft tabs not used on line 85
    ERROR: two-space soft tabs not used on line 86
    ERROR: two-space soft tabs not used on line 87
    ERROR: two-space soft tabs not used on line 88
    ERROR: two-space soft tabs not used on line 89
    ERROR: two-space soft tabs not used on line 90
    ERROR: two-space soft tabs not used on line 91
    ERROR: two-space soft tabs not used on line 92
    ERROR: two-space soft tabs not used on line 93
    ERROR: two-space soft tabs not used on line 94
    ERROR: two-space soft tabs not used on line 95
    ERROR: two-space soft tabs not used on line 96
    ERROR: two-space soft tabs not used on line 97
    ERROR: two-space soft tabs not used on line 98
    ERROR: two-space soft tabs not used on line 99
    ERROR: two-space soft tabs not used on line 100
    ERROR: two-space soft tabs not used on line 101
    ERROR: two-space soft tabs not used on line 102
    ERROR: two-space soft tabs not used on line 103
    ERROR: two-space soft tabs not used on line 104
    ERROR: two-space soft tabs not used on line 105
    ERROR: two-space soft tabs not used on line 106
    ERROR: two-space soft tabs not used on line 107
    ERROR: two-space soft tabs not used on line 108
    ERROR: two-space soft tabs not used on line 109
    ERROR: two-space soft tabs not used on line 110
    WARNING: indentation of => is not properly aligned on line 162
    WARNING: indentation of => is not properly aligned on line 163
    WARNING: indentation of => is not properly aligned on line 164
    WARNING: indentation of => is not properly aligned on line 165
    WARNING: ensure found on line but it's not the first attribute on line 203